<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import AdminPageFrame from "../components/AdminPageFrame.vue";
import { adminApi, adminErrorMessage, formatDate } from "../api";
import type { ReviewDetail, ReviewHistoryEvent, ReviewItem, ReviewStatus } from "../../shared/types";
import LoadingState from "../../shared/components/LoadingState.vue";
import ErrorState from "../../shared/components/ErrorState.vue";
import EmptyState from "../../shared/components/EmptyState.vue";
import RetryButton from "../../shared/components/RetryButton.vue";
import StatusBadge from "../../shared/components/StatusBadge.vue";
import InlineNotice from "../../shared/components/InlineNotice.vue";

const page = ref(0); const size = 20; const total = ref(0); const items = ref<ReviewItem[]>([]); const loading = ref(true); const error = ref(""); const notice = ref("");
const filters = reactive({ search: "", status: "", type: "" }); const selected = ref<ReviewDetail | null>(null); const history = ref<ReviewHistoryEvent[]>([]); const detailLoading = ref(false); const actionBusy = ref(false); const nextStatus = ref<ReviewStatus>("DRAFT"); const note = ref("");
const statuses: ReviewStatus[] = ["LEGACY_UNVERIFIED", "DRAFT", "PUBLISHED", "VERIFIED", "EXCLUDED"];
function noticeTone(value: string): "success" | "danger" { return value.includes("未完成") || value.includes("失败") ? "danger" : "success"; }
async function load() { loading.value = true; error.value = ""; try { const result = await adminApi.reviews({ page: page.value, size, search: filters.search, status: filters.status, type: filters.type }); items.value = result.items; total.value = result.total; } catch (failure) { error.value = adminErrorMessage(failure, "读取审核队列"); } finally { loading.value = false; } }
function applyFilters() { page.value = 0; void load(); }
async function openDetail(item: ReviewItem) { detailLoading.value = true; selected.value = { item, sourceChain: [] }; history.value = []; notice.value = ""; try { const [detail, events] = await Promise.all([adminApi.review(item.type, item.id), adminApi.reviewHistory(item.type, item.id)]); selected.value = detail; history.value = events; nextStatus.value = detail.item.status; note.value = ""; } catch (failure) { selected.value = null; notice.value = adminErrorMessage(failure, "读取审核详情"); } finally { detailLoading.value = false; } }
async function updateStatus() { if (!selected.value) return; if (!window.confirm(`确认将 ${selected.value.item.title} 变更为 ${nextStatus.value}？来源链完整性和发布规则仍由服务端最终校验。`)) return; actionBusy.value = true; notice.value = ""; try { const updated = await adminApi.updateReviewStatus(selected.value.item.type, selected.value.item.id, { status: nextStatus.value, note: note.value || null }); selected.value.item = updated; items.value = items.value.map((item) => item.id === updated.id && item.type === updated.type ? updated : item); history.value = await adminApi.reviewHistory(updated.type, updated.id); notice.value = "审核状态已更新。"; } catch (failure) { notice.value = adminErrorMessage(failure, "更新审核状态"); } finally { actionBusy.value = false; } }
function tone(status: ReviewStatus): "success" | "danger" | "warning" | "neutral" { return status === "VERIFIED" || status === "PUBLISHED" ? "success" : status === "EXCLUDED" ? "danger" : status === "DRAFT" ? "warning" : "neutral"; }
onMounted(load);
</script>

<template>
  <AdminPageFrame title="证据与资源审核" description="审核队列只展示后端返回的真实项目、来源链和历史。VERIFIED 的完整性规则由服务端决定。">
    <template #actions><button class="button button--small" type="button" :disabled="loading" @click="load">刷新</button></template>
    <form class="admin-toolbar" @submit.prevent="applyFilters"><label class="admin-field admin-field--wide"><span>搜索</span><input v-model="filters.search" maxlength="160" placeholder="标题或标识" /></label><label class="admin-field"><span>类型</span><select v-model="filters.type"><option value="">全部类型</option><option value="RESOURCE">RESOURCE</option><option value="KNOWLEDGE_CHUNK">KNOWLEDGE_CHUNK</option><option value="PRESENTATION_MANIFEST">PRESENTATION_MANIFEST</option><option value="PRESENTATION_PAGE">PRESENTATION_PAGE</option><option value="DSVP_REQUEST_SNAPSHOT">DSVP_REQUEST_SNAPSHOT</option></select></label><label class="admin-field"><span>状态</span><select v-model="filters.status"><option value="">全部状态</option><option v-for="status in statuses" :key="status" :value="status">{{ status }}</option></select></label><button class="button button--primary" type="submit" :disabled="loading">筛选</button></form>
    <InlineNotice v-if="notice" :message="notice" :tone="noticeTone(notice)" />
    <LoadingState v-if="loading" label="正在读取审核队列…" /><ErrorState v-else-if="error" title="审核队列读取失败" :message="error"><RetryButton @retry="load" /></ErrorState><EmptyState v-else-if="!items.length" title="审核队列为空" message="当前筛选条件没有待处理项目。" />
    <section v-else class="admin-table-wrap"><table class="admin-table"><thead><tr><th>项目</th><th>状态</th><th>来源链</th><th>更新时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="`${item.type}-${item.id}`"><td><strong>{{ item.title }}</strong><div class="admin-muted">{{ item.type }} · {{ item.id }}</div></td><td><StatusBadge :label="item.status" :tone="tone(item.status)" /></td><td><StatusBadge :label="item.sourceComplete ? '完整' : '不完整'" :tone="item.sourceComplete ? 'success' : 'warning'" /></td><td>{{ formatDate(item.updatedAt) }}</td><td><button class="button button--small" type="button" data-action="open-review" @click="openDetail(item)">查看详情</button></td></tr></tbody></table></section>
    <div class="admin-pagination"><span>第 {{ page + 1 }} 页 · 共 {{ total }} 条</span><div class="admin-pagination__actions"><button class="button button--small" type="button" :disabled="page === 0 || loading" @click="page--; load()">上一页</button><button class="button button--small" type="button" :disabled="(page + 1) * size >= total || loading" @click="page++; load()">下一页</button></div></div>
    <aside v-if="selected" class="admin-detail"><div class="admin-detail__header"><div><h2>{{ selected.item.title }}</h2><p>{{ selected.item.type }} · {{ selected.item.id }}</p></div><button class="button button--small" type="button" @click="selected = null">关闭</button></div><div v-if="detailLoading" data-state="review-detail-loading"><LoadingState label="正在读取来源链…" /></div><template v-else><dl><dt>当前状态</dt><dd><StatusBadge :label="selected.item.status" :tone="tone(selected.item.status)" /></dd><dt>章节</dt><dd>{{ selected.item.chapterId || "未关联" }}</dd><dt>来源链</dt><dd>{{ selected.item.sourceComplete ? "完整" : "不完整" }}</dd></dl><h3>来源链</h3><ul class="admin-list"><li v-for="source in selected.sourceChain" :key="`${source.type}-${source.id}`"><strong>{{ source.title }}</strong><div class="admin-muted">{{ source.type }} · {{ source.id }} · {{ source.status }}</div></li><li v-if="!selected.sourceChain.length" class="admin-muted">服务未返回来源链。</li></ul><h3>状态变更</h3><div class="admin-form__grid"><label class="admin-field"><span>目标状态</span><select v-model="nextStatus" data-field="next-status"><option v-for="status in statuses" :key="status" :value="status">{{ status }}</option></select></label><label class="admin-field"><span>审核备注</span><input v-model="note" maxlength="500" placeholder="可选，说明审核依据" /></label></div><button class="button button--primary" type="button" data-action="update-review" :disabled="actionBusy" @click="updateStatus">{{ actionBusy ? "提交中…" : "提交状态变更" }}</button><h3>审核历史</h3><ul class="admin-list"><li v-for="event in history" :key="event.id"><strong>{{ event.previousStatus }} → {{ event.nextStatus }}</strong><div class="admin-muted">{{ formatDate(event.createdAt) }} · {{ event.note || "无备注" }} · requestId {{ event.requestId }}</div></li><li v-if="!history.length" class="admin-muted">暂无审核历史。</li></ul></template></aside>
  </AdminPageFrame>
</template>
